name: AegisterVPN
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  http:
  flutter_web_auth_2: ^4.0.0-alpha.0
  path_provider: ^2.1.4
  url_launcher: ^6.0.3
  logger: ^2.5.0
  shared_preferences:
  flutter:
    sdk: flutter

  # Cupertino style icons
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.3.0

  # Encourages good practices
  flutter_lints: ^4.0.0

flutter:
  # Enabling material design
  uses-material-design: true
  generate: true

  # App assets
  assets:
    - assets/
    - assets/images/